# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run:
      - command: |
            echo 'export PATH=/path/to/foo/bin:"$PATH"' >> "$BASH_ENV"
            echo "export VERY_IMPORTANT=VALUE_CONTENT" >> "$BASH_ENV"
            source "$BASH_ENV
      - run:
          command: npm run dev
      - run:
          command: npm test
      


  
        
          
