# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.11.0
    parallelism: 4
    resource_class: large
    steps:
      - run: mkdir ~/junit
      - checkout
      - run: TEST=$(circleci tests glob "src/__tests__/*.js" | circleci tests split --split-by=timings)
      - run: npm test


   



  
        
          
